# PostCVPR mode training configuration
# Inherits common settings from _base.yaml

defaults:
  - _base

experiment:
  name: debug
  save_checkpoint_every: 2000
  n_epochs: 20000000
  max_iter: 60000

dataloader:
  num_workers: 8
  batch_size: 1
  pyg_data: True
  dataset:
    postcvpr:
      data_root: 'vto_dataset/smpl_parameters'
      smpl_model: 'smpl/SMPL_FEMALE.pkl'
      garment_dict_file: 'garments_dict.pkl'
      obstacle_dict_file: 'smpl_aux.pkl'
      split_path: 'datasplits/train.csv'
      lookup_steps: 5
      pinned_verts: True
      random_betas: True
      betas_scale: 3.
      n_coarse_levels: 3
